"use client";

import React, { useState, useMemo } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { AnimatePresence } from "framer-motion";
import BrandCard from "@/components/BrandCard";
import FilterModal, { FilterSidebar } from "@/components/FilterModal";
import { useAuth } from "@/context/AuthContext";
import { calculateBrandMatchScore } from "@/utils/matchScore";

export default function DiscoverBrands() {
  const { profile } = useAuth();
  // --- FILTER STATES ---
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategories, setSelectedCategories] = useState([]);
  const [budgetRange, setBudgetRange] = useState({ min: 0, max: 10000 });
  const [selectedPlatforms, setSelectedPlatforms] = useState([]);
  const [isVerifiedOnly, setIsVerifiedOnly] = useState(false);
  const [isFiltersOpen, setIsFiltersOpen] = useState(false);

  // --- FILTER ENGINE ---
  const filteredBrands = useMemo(() => {
    return BRANDS.filter((brand) => {
      const matchesSearch = brand.name
        .toLowerCase()
        .includes(searchQuery.toLowerCase());
      const matchesCategory =
        selectedCategories.length === 0 || selectedCategories.includes(brand.category);
      const matchesBudget =
        brand.minBudget >= budgetRange.min &&
        brand.minBudget <= budgetRange.max;
      const matchesVerified = isVerifiedOnly ? brand.isVerified : true;
      const matchesPlatform =
        selectedPlatforms.length === 0 ||
        brand.platforms.some((p) => selectedPlatforms.includes(p));

      return (
        matchesSearch &&
        matchesCategory &&
        matchesBudget &&
        matchesVerified &&
        matchesPlatform
      );
    });
  }, [
    searchQuery,
    selectedCategories,
    budgetRange,
    isVerifiedOnly,
    selectedPlatforms,
  ]);

  const resetFilters = () => {
    setSearchQuery("");
    setSelectedCategories([]);
    setBudgetRange({ min: 0, max: 10000 });
    setSelectedPlatforms([]);
    setIsVerifiedOnly(false);
  };

  return (
    <div className="min-h-screen bg-[#F8F9FD] p-4 lg:p-8 lg:pt-24 font-sans relative">
      <div className="max-w-[1440px] mx-auto space-y-8">
        {/* Header - Mobile Only */}
        <div className="lg:hidden flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-slate-800">Discover Brands</h1>
          <Button
            variant="outline"
            onClick={() => setIsFiltersOpen(true)}
            className="h-12 w-12 rounded-xl border-none bg-white shadow-sm shrink-0"
          >
            <SlidersHorizontal size={20} />
          </Button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* --- LEFT SIDEBAR (Desktop) --- */}
          <aside className="hidden lg:block lg:col-span-3 space-y-8 sticky top-8">
            <div className="relative group">
              <Search
                className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-[#E60076]"
                size={20}
              />
              <Input
                placeholder="Search..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-12 h-14 bg-white border-none rounded-2xl shadow-sm text-sm font-medium"
              />
            </div>

            <FilterSidebar
              selectedCategories={selectedCategories}
              setSelectedCategories={setSelectedCategories}
              budgetRange={budgetRange}
              setBudgetRange={setBudgetRange}
              selectedPlatforms={selectedPlatforms}
              setSelectedPlatforms={setSelectedPlatforms}
              isVerifiedOnly={isVerifiedOnly}
              setIsVerifiedOnly={setIsVerifiedOnly}
              onExpand={() => setIsFiltersOpen(true)}
            />

          </aside>

          {/* --- RIGHT CONTENT --- */}
          <main className="lg:col-span-9 space-y-8">

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <AnimatePresence>
                {filteredBrands.map((brand) => (
                  <BrandCard key={brand.id} brand={brand} matchScore={calculateBrandMatchScore(profile, brand)} />
                ))}
              </AnimatePresence>
            </div>

            {filteredBrands.length === 0 && (
              <div className="text-center py-20 bg-white rounded-[32px] text-slate-400 font-bold">
                No brands match these filters.
              </div>
            )}
          </main>
        </div>
      </div>

      <AnimatePresence>
        {isFiltersOpen && (
          <FilterModal
            onClose={() => setIsFiltersOpen(false)}
            selectedCategories={selectedCategories}
            setSelectedCategories={setSelectedCategories}
            budgetRange={budgetRange}
            setBudgetRange={setBudgetRange}
            selectedPlatforms={selectedPlatforms}
            setSelectedPlatforms={setSelectedPlatforms}
            isVerifiedOnly={isVerifiedOnly}
            setIsVerifiedOnly={setIsVerifiedOnly}
          />
        )}
      </AnimatePresence>
    </div>
  );
}

const BRANDS = [
  {
    id: 1,
    name: "D LUXE PERFUMES",
    category: "Perfume",
    minBudget: 1500,
    maxBudget: 7500,
    isVerified: true,
    platforms: ["Instagram"],
    activeCampaigns: 12,
    rating: 4.9,
    followers: "45K",
    logo: "https://lh3.googleusercontent.com/d/1y5nOHRt1P-5SB6BCzryeczgmhyoHcuSs",
    payout: "₹1,500 - ₹7,500",
  },
  {
    id: 2,
    name: "ZAUDI",
    category: "Perfume",
    minBudget: 1000,
    maxBudget: 5000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.3,
    followers: "12K",
    logo: "https://lh3.googleusercontent.com/d/1PS9A-rPC48WUPo8imZjw4XAzChADsceu",
    payout: "₹1,000 - ₹5,000",
  },
  {
    id: 3,
    name: "RIAR ELUX",
    category: "Wellness",
    minBudget: 2000,
    maxBudget: 8000,
    isVerified: true,
    platforms: ["Instagram"],
    activeCampaigns: 8,
    rating: 4.7,
    followers: "28K",
    logo: "https://lh3.googleusercontent.com/d/1cUytBemciPv8OdMi6-gADzUCKzfymr1R",
    payout: "₹2,000 - ₹8,000",
  },
  {
    id: 4,
    name: "BIODANCE",
    category: "Skincare",
    minBudget: 3000,
    maxBudget: 12000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 15,
    rating: 4.8,
    followers: "85K",
    logo: "https://lh3.googleusercontent.com/d/16kk2EEAMw_Y0D3Jo4BCUKAwF2rE8ugLG",
    payout: "₹3,000 - ₹12,000",
  },
  {
    id: 5,
    name: "SESA POWERPLUS",
    category: "Health",
    minBudget: 1200,
    maxBudget: 6000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.5,
    followers: "19K",
    logo: "https://lh3.googleusercontent.com/d/1ua9IVd7PYxaIP44G3XHLKgauW5VgTy2r",
    payout: "₹1,200 - ₹6,000",
  },
  {
    id: 6,
    name: "SESA AYURVEDIC",
    category: "Health",
    minBudget: 1500,
    maxBudget: 7000,
    isVerified: true,
    platforms: ["Instagram"],
    activeCampaigns: 10,
    rating: 4.6,
    followers: "52K",
    logo: "https://lh3.googleusercontent.com/d/1ua9IVd7PYxaIP44G3XHLKgauW5VgTy2r",
    payout: "₹1,500 - ₹7,000",
  },
  {
    id: 7,
    name: "JSR Group of Hotels",
    category: "Hotel",
    minBudget: 5000,
    maxBudget: 20000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.8,
    followers: "34K",
    logo: "https://lh3.googleusercontent.com/d/14oE-4ohZxzmshUK6LwU8N3l5tOkh6jcT",
    payout: "₹5,000 - ₹20,000",
  },
  {
    id: 8,
    name: "Crismson Curry",
    category: "Cafe",
    minBudget: 1000,
    maxBudget: 4500,
    isVerified: true,
    platforms: ["Instagram"],
    activeCampaigns: 9,
    rating: 4.4,
    followers: "7.5K",
    logo: "https://lh3.googleusercontent.com/d/1rUYya-EIZPqE7lSZBa_TY_wKI5httO6H",
    payout: "₹1,000 - ₹4,500",
  },
  {
    id: 9,
    name: "AURIC",
    category: "Health",
    minBudget: 2500,
    maxBudget: 9000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 14,
    rating: 4.9,
    followers: "120K",
    logo: "https://lh3.googleusercontent.com/d/1IuS3e9tDzB987BNDkQaEmVLkg6IYDiuy",
    payout: "₹2,500 - ₹9,000",
  },
  {
    id: 10,
    name: "ASTER ORGANICS",
    category: "Perfume",
    minBudget: 800,
    maxBudget: 3000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.2,
    followers: "2.5K",
    logo: "",
    payout: "₹800 - ₹3,000",
  },
  {
    id: 11,
    name: "FITKG",
    category: "Tea",
    minBudget: 600,
    maxBudget: 2500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.1,
    followers: "5K",
    logo: "",
    payout: "₹600 - ₹2,500",
  },
  {
    id: 12,
    name: "VALRON",
    category: "Clothing",
    minBudget: 1500,
    maxBudget: 5500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.4,
    followers: "18K",
    logo: "",
    payout: "₹1,500 - ₹5,500",
  },
  {
    id: 13,
    name: "HENOSIS",
    category: "Diffuser Oil",
    minBudget: 900,
    maxBudget: 3500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.5,
    followers: "1.2K",
    logo: "",
    payout: "₹900 - ₹3,500",
  },
  {
    id: 14,
    name: "ARTH CAFE",
    category: "Cafe",
    minBudget: 1000,
    maxBudget: 4000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.6,
    followers: "11K",
    logo: "",
    payout: "₹1,000 - ₹4,000",
  },
  {
    id: 15,
    name: "THREAD CRAFTERS",
    category: "Clothing",
    minBudget: 2000,
    maxBudget: 7500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.3,
    followers: "9.8K",
    logo: "",
    payout: "₹2,000 - ₹7,500",
  },
  {
    id: 16,
    name: "COVERTOK",
    category: "Phone Accessories",
    minBudget: 500,
    maxBudget: 2200,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 7,
    rating: 4.7,
    followers: "14.2K",
    logo: "",
    payout: "₹500 - ₹2,200",
  },
  {
    id: 17,
    name: "AUREMI",
    category: "Hair Care",
    minBudget: 1800,
    maxBudget: 6000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.4,
    followers: "6.1K",
    logo: "",
    payout: "₹1,800 - ₹6,000",
  },
  {
    id: 18,
    name: "PAPPILIO",
    category: "Hair Care",
    minBudget: 1500,
    maxBudget: 5000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.5,
    followers: "22K",
    logo: "",
    payout: "₹1,500 - ₹5,000",
  },
  {
    id: 19,
    name: "FABCO BAG",
    category: "Bag",
    minBudget: 1000,
    maxBudget: 4000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.2,
    followers: "4.3K",
    logo: "",
    payout: "₹1,000 - ₹4,000",
  },
  {
    id: 20,
    name: "LUMINARA",
    category: "Skincare",
    minBudget: 2000,
    maxBudget: 8000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.6,
    followers: "31K",
    logo: "",
    payout: "₹2,000 - ₹8,000",
  },
  {
    id: 21,
    name: "VELLASIO",
    category: "Skincare",
    minBudget: 1800,
    maxBudget: 7000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.3,
    followers: "7.5K",
    logo: "",
    payout: "₹1,800 - ₹7,000",
  },
  {
    id: 22,
    name: "BLANCH & SAUTE",
    category: "Cafe",
    minBudget: 1200,
    maxBudget: 5000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.5,
    followers: "15K",
    logo: "",
    payout: "₹1,200 - ₹5,000",
  },
  {
    id: 23,
    name: "GRANNY DEN RESORT",
    category: "Resort",
    minBudget: 4000,
    maxBudget: 15000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.7,
    followers: "26K",
    logo: "",
    payout: "₹4,000 - ₹15,000",
  },
  {
    id: 24,
    name: "ITHARNA RESORT",
    category: "Resort",
    minBudget: 5000,
    maxBudget: 18000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.8,
    followers: "32K",
    logo: "",
    payout: "₹5,000 - ₹18,000",
  },
  {
    id: 25,
    name: "RIVERDALE RESORT",
    category: "Resort",
    minBudget: 3500,
    maxBudget: 14000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.5,
    followers: "21K",
    logo: "",
    payout: "₹3,500 - ₹14,000",
  },
  {
    id: 26,
    name: "LAMPLIGHTER CAFE",
    category: "Cafe",
    minBudget: 900,
    maxBudget: 3800,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.4,
    followers: "8.2K",
    logo: "",
    payout: "₹900 - ₹3,800",
  },
  {
    id: 27,
    name: "BLUEWIND RESORT",
    category: "Resort",
    minBudget: 4500,
    maxBudget: 16000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.6,
    followers: "14K",
    logo: "",
    payout: "₹4,500 - ₹16,000",
  },
  {
    id: 28,
    name: "TONIC",
    category: "Cafe",
    minBudget: 1200,
    maxBudget: 5000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.7,
    followers: "19.5K",
    logo: "",
    payout: "₹1,200 - ₹5,000",
  },
  {
    id: 29,
    name: "NEW ATTRACTION SALON",
    category: "Salon",
    minBudget: 1000,
    maxBudget: 6000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.3,
    followers: "11K",
    logo: "",
    payout: "₹1,000 - ₹6,000",
  },
  {
    id: 30,
    name: "RANGREZA CAFE",
    category: "Cafe",
    minBudget: 800,
    maxBudget: 3500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.2,
    followers: "5.4K",
    logo: "",
    payout: "₹800 - ₹3,500",
  },
  {
    id: 31,
    name: "AARYAM RESORTS",
    category: "Resort",
    minBudget: 5500,
    maxBudget: 22000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.9,
    followers: "42K",
    logo: "",
    payout: "₹5,500 - ₹22,000",
  },
  {
    id: 32,
    name: "HEAVEN SKYLOUNGE",
    category: "Skylounge",
    minBudget: 3000,
    maxBudget: 11000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.6,
    followers: "25K",
    logo: "",
    payout: "₹3,000 - ₹11,000",
  },
  {
    id: 33,
    name: "ROYAL DEN",
    category: "Cafe",
    minBudget: 900,
    maxBudget: 4000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.4,
    followers: "6.8K",
    logo: "",
    payout: "₹900 - ₹4,000",
  },
  {
    id: 34,
    name: "REGENTA",
    category: "Hotel",
    minBudget: 6000,
    maxBudget: 25000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 8,
    rating: 4.5,
    followers: "55K",
    logo: "",
    payout: "₹6,000 - ₹25,000",
  },
  {
    id: 35,
    name: "STUDIO XO",
    category: "Cafe",
    minBudget: 2500,
    maxBudget: 9500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 10,
    rating: 4.7,
    followers: "68K",
    logo: "",
    payout: "₹2,500 - ₹9,500",
  },
  {
    id: 36,
    name: "THE ROYAL MAN CO",
    category: "Skincare",
    minBudget: 1500,
    maxBudget: 6000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.4,
    followers: "12K",
    logo: "",
    payout: "₹1,500 - ₹6,000",
  },
  {
    id: 37,
    name: "SILENT BISTRO",
    category: "Cafe",
    minBudget: 1000,
    maxBudget: 4500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.5,
    followers: "14K",
    logo: "",
    payout: "₹1,000 - ₹4,500",
  },
  {
    id: 38,
    name: "VISHRAM RESORT",
    category: "Resort",
    minBudget: 4000,
    maxBudget: 16000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.6,
    followers: "18K",
    logo: "",
    payout: "₹4,000 - ₹16,000",
  },
  {
    id: 39,
    name: "LUX BY HEAVEN",
    category: "Hotel",
    minBudget: 3500,
    maxBudget: 14000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.5,
    followers: "16.5K",
    logo: "",
    payout: "₹3,500 - ₹14,000",
  },
  {
    id: 40,
    name: "PEARLITO",
    category: "Accessories",
    minBudget: 700,
    maxBudget: 3000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.2,
    followers: "4.9K",
    logo: "",
    payout: "₹700 - ₹3,000",
  },
  {
    id: 41,
    name: "THE BATH & CARE",
    category: "Haircare",
    minBudget: 1500,
    maxBudget: 6500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.4,
    followers: "13.2K",
    logo: "",
    payout: "₹1,500 - ₹6,500",
  },
  {
    id: 42,
    name: "PRC PERFUMES",
    category: "Perfume",
    minBudget: 1000,
    maxBudget: 4800,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.1,
    followers: "6.5K",
    logo: "",
    payout: "₹1,000 - ₹4,800",
  },
  {
    id: 43,
    name: "MHEKO",
    category: "Diffuser Oil",
    minBudget: 800,
    maxBudget: 3200,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.3,
    followers: "3.8K",
    logo: "",
    payout: "₹800 - ₹3,200",
  },
  {
    id: 44,
    name: "AASHAPURA BIOTECH",
    category: "Health",
    minBudget: 2000,
    maxBudget: 9000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.5,
    followers: "21K",
    logo: "",
    payout: "₹2,000 - ₹9,000",
  },
  {
    id: 45,
    name: "WELLINGTON TEA",
    category: "Tea",
    minBudget: 600,
    maxBudget: 2800,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.3,
    followers: "9.4K",
    logo: "",
    payout: "₹600 - ₹2,800",
  },
  {
    id: 46,
    name: "CHIMPAAANZEE",
    category: "Clothing",
    minBudget: 1200,
    maxBudget: 5500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.4,
    followers: "16K",
    logo: "",
    payout: "₹1,200 - ₹5,500",
  },
  {
    id: 47,
    name: "HI PROTECH",
    category: "Phone Accessories",
    minBudget: 500,
    maxBudget: 2500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.2,
    followers: "7.2K",
    logo: "",
    payout: "₹500 - ₹2,500",
  },
  {
    id: 48,
    name: "BIO SKINSY",
    category: "Skincare",
    minBudget: 1500,
    maxBudget: 6000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.1,
    followers: "5.5K",
    logo: "",
    payout: "₹1,500 - ₹6,000",
  },
  {
    id: 49,
    name: "YOU SKINCARE",
    category: "Skincare",
    minBudget: 1800,
    maxBudget: 7500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.4,
    followers: "13K",
    logo: "",
    payout: "₹1,800 - ₹7,500",
  },
  {
    id: 50,
    name: "NATURE FLAVOURS",
    category: "Resort",
    minBudget: 3000,
    maxBudget: 12000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.5,
    followers: "10.5K",
    logo: "",
    payout: "₹3,000 - ₹12,000",
  },
  {
    id: 51,
    name: "ELVORA PERFUMES",
    category: "Perfumes",
    minBudget: 1000,
    maxBudget: 4500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 1,
    rating: 4.0,
    followers: "1.2K",
    logo: "",
    payout: "₹1,000 - ₹4,500",
  },
  {
    id: 52,
    name: "RIBI ORGANICS",
    category: "Skincare",
    minBudget: 1500,
    maxBudget: 6500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.6,
    followers: "18.2K",
    logo: "",
    payout: "₹1,500 - ₹6,500",
  },
  {
    id: 53,
    name: "SARIN STATE",
    category: "Hotel",
    minBudget: 5000,
    maxBudget: 20000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.7,
    followers: "28K",
    logo: "",
    payout: "₹5,000 - ₹20,000",
  },
  {
    id: 54,
    name: "TRUMPYINDIA",
    category: "Adventure Park",
    minBudget: 2000,
    maxBudget: 8500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 7,
    rating: 4.8,
    followers: "52K",
    logo: "",
    payout: "₹2,000 - ₹8,500",
  },
  {
    id: 55,
    name: "ADVAYA STAYS",
    category: "Airbnb",
    minBudget: 2500,
    maxBudget: 10000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.6,
    followers: "9.2K",
    logo: "",
    payout: "₹2,500 - ₹10,000",
  },
  {
    id: 56,
    name: "KESH ART",
    category: "Skincare",
    minBudget: 1200,
    maxBudget: 5000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.3,
    followers: "11.5K",
    logo: "",
    payout: "₹1,200 - ₹5,000",
  },
  {
    id: 57,
    name: "WELLI HABITS",
    category: "Health",
    minBudget: 1500,
    maxBudget: 7000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.5,
    followers: "14.8K",
    logo: "",
    payout: "₹1,500 - ₹7,000",
  },
  {
    id: 58,
    name: "AURORA HOMESTAY",
    category: "Airbnb",
    minBudget: 2000,
    maxBudget: 8000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 2,
    rating: 4.6,
    followers: "4.1K",
    logo: "",
    payout: "₹2,000 - ₹8,000",
  },
  {
    id: 59,
    name: "TEHRI LAKE",
    category: "Adventure Park",
    minBudget: 3000,
    maxBudget: 12000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.7,
    followers: "65K",
    logo: "",
    payout: "₹3,000 - ₹12,000",
  },
  {
    id: 60,
    name: "CLOUD DECK",
    category: "Hotel",
    minBudget: 4500,
    maxBudget: 18000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.5,
    followers: "18.5K",
    logo: "",
    payout: "₹4,500 - ₹18,000",
  },
  {
    id: 61,
    name: "SOMESH",
    category: "Airbnb",
    minBudget: 1500,
    maxBudget: 6000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 1,
    rating: 4.2,
    followers: "2.4K",
    logo: "",
    payout: "₹1,500 - ₹6,000",
  },
  {
    id: 62,
    name: "ST JAMES COURT BEACH RESORT",
    category: "Resort",
    minBudget: 5500,
    maxBudget: 22000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.6,
    followers: "31K",
    logo: "",
    payout: "₹5,500 - ₹22,000",
  },
  {
    id: 63,
    name: "NOSTALGIC",
    category: "Airbnb",
    minBudget: 1800,
    maxBudget: 7500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.4,
    followers: "6.2K",
    logo: "",
    payout: "₹1,800 - ₹7,500",
  },
  {
    id: 64,
    name: "MUGLY CAFE",
    category: "Cafe",
    minBudget: 1000,
    maxBudget: 4500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.6,
    followers: "12.5K",
    logo: "",
    payout: "₹1,000 - ₹4,500",
  },
  {
    id: 65,
    name: "SUGAR CUP",
    category: "Cafe",
    minBudget: 800,
    maxBudget: 3500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.5,
    followers: "10.2K",
    logo: "",
    payout: "₹800 - ₹3,500",
  },
  {
    id: 66,
    name: "HABIVANA",
    category: "Airbnb",
    minBudget: 3000,
    maxBudget: 12000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.7,
    followers: "15.8K",
    logo: "",
    payout: "₹3,000 - ₹12,000",
  },
  {
    id: 67,
    name: "MR MILK",
    category: "Milk",
    minBudget: 1000,
    maxBudget: 5000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 8,
    rating: 4.8,
    followers: "45K",
    logo: "",
    payout: "₹1,000 - ₹5,000",
  },
  {
    id: 68,
    name: "WHITELOTUS PURKUL",
    category: "Hotel",
    minBudget: 4500,
    maxBudget: 16000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.6,
    followers: "19.2K",
    logo: "",
    payout: "₹4,500 - ₹16,000",
  },
  {
    id: 69,
    name: "JOLLY RETREAT",
    category: "Resort",
    minBudget: 3500,
    maxBudget: 13000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.4,
    followers: "12.8K",
    logo: "",
    payout: "₹3,500 - ₹13,000",
  },
  {
    id: 70,
    name: "KASHAYAH GREENS",
    category: "Tea",
    minBudget: 700,
    maxBudget: 3200,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.3,
    followers: "6.1K",
    logo: "",
    payout: "₹700 - ₹3,200",
  },
  {
    id: 71,
    name: "MOKSHAM STAYS",
    category: "Resort",
    minBudget: 5000,
    maxBudget: 19000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.7,
    followers: "24K",
    logo: "",
    payout: "₹5,000 - ₹19,000",
  },
  {
    id: 72,
    name: "AQUA OUTBACK",
    category: "Adventure Park",
    minBudget: 3500,
    maxBudget: 14000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 6,
    rating: 4.8,
    followers: "32K",
    logo: "",
    payout: "₹3,500 - ₹14,000",
  },
  {
    id: 73,
    name: "KIYO BEAUTY",
    category: "Skincare",
    minBudget: 2000,
    maxBudget: 8500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 10,
    rating: 4.7,
    followers: "41K",
    logo: "",
    payout: "₹2,000 - ₹8,500",
  },
  {
    id: 74,
    name: "ZADAP",
    category: "Appliances",
    minBudget: 1200,
    maxBudget: 7000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 4,
    rating: 4.4,
    followers: "15.5K",
    logo: "",
    payout: "₹1,200 - ₹7,000",
  },
  {
    id: 75,
    name: "JUVIA JEWELLERY",
    category: "Jewellery",
    minBudget: 1500,
    maxBudget: 9000,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 5,
    rating: 4.6,
    followers: "22.4K",
    logo: "",
    payout: "₹1,500 - ₹9,000",
  },
  {
    id: 76,
    name: "CLAGG & ASCLEPIUS",
    category: "Skincare",
    minBudget: 1400,
    maxBudget: 5500,
    isVerified: false,
    platforms: ["Instagram"],
    activeCampaigns: 3,
    rating: 4.2,
    followers: "7.8K",
    logo: "",
    payout: "₹1,400 - ₹5,500",
  },
];
